### ISSUE TITLE
Система логирования для чекера (инфографика)

### ISSUE THREAD

**Issue by leins275** [PrimatElite/ml-labs#7]
Придумать, что выводить по результатам сравнения результата плейсера с результатом чекера.

Надо понять, как хранить и собирать статистику по работе нашего чекера с различными плейсерами.

**Comment by ExpressFromSiberia** [comment]
1 этап:
Если мы хотим иллюстрировать его отдельно, то мы можем вывести результаты в виде таблицы, например, где находятся "точки разрыва" для каждого артефакта в общей системе, т.е. мы переводим диапазоны значений в % и выводим интервалы "зеленой" и "красной" зон для каждого артефакта. Это покажет нам какой артефакт имеет большее влияние на результат, а какой почти ничего не меняет.
* Нужно ли нам это - вопрос открытый, т.к. мы не изучением артефактов занимаемся.

2 этап:
Суть тестирования сводится к кейсам. Я думаю, будет правильно сделать тестирование таким: сначала мы рассмотрим 2 случая со значениями артефактов из "хорошей" зоны - для левой границы зоны и среднего значения, потом 2 случая из "плохой" - для среднего значения и правой границы и 3 случая для диапазона "точек разрыва" - граничные значения и среднее значение, а также несколько тестов со смешанными значениями. Полученные результаты отразим в графиках с барами, отражающими % верных ответов в каждой зоне для отношения {кейс-процент верных ответов}.
